### ISSUE TITLE
Latest version of package

### ISSUE THREAD

**Issue by devzhk** [tensordiffeq/TensorDiffEq#28]
The examples in the doc use the latest code of master branch but the library on Pypi is still the version in May. Can you build the lib and update the version on Pypi?

**Comment by levimcclenny** [comment]
You are correct. This will happen this week. Will wait to close this until I push it. Thanks!

**Comment by levimcclenny** [comment]
@devzhk completed. Updating docs at tensordifffeq.io later this week. Most functionality will remain the same, however interfacing with SA weighting will look different. 

Please provide feedback, feel free to contribute, and let us know how you're using tdq for your own research if applicable.

**Comment by devzhk** [comment]
Thanks for pushing it. I'm trying to use SA-PINNs to solve Kolmogrov Flow. But the gradient is always None in my implementation.  It seems that tensordiffeq uses static graph for computing derivatives. Do you know how to check the gradient flow with static graph? Debugging by setting breakpoint only seems to work with dynamic graph.

**Comment by levimcclenny** [comment]
The gradients for the self-adaptive weights are None? This is interesting... that shouldn't happen.

Unfortunately determining gradient flow in a static graph is something I have also been working on recently to little avail. Saving the gradient flow output at a time step, etc doesn't work too well I have found if you're operating in a static graph. Makes debugging and plotting things difficult. 

Perhaps starting with the original code for the SA-PINNs paper would be helpful for you, its written in a dynamic graph - https://github.com/levimcclenny/SA-PINNs

**Comment by devzhk** [comment]
Thanks for your kind suggestion. Will try it.
