### ISSUE TITLE
model.save ?

### ISSUE THREAD

**Issue by ragusa** [tensordiffeq/TensorDiffEq#3]
Sometimes, it's useful to save the model for later use. I couldn't find a .save method and pickle (and dill) didn't let me dump the object for later re-use. (example of error with pickle: Can't pickle local object 'make_gradient_clipnorm_fn.<locals>.<lambda>').

Is it currently possible to save the model? Thanks!

**Comment by levimcclenny** [comment]
completed, ref #4 

Thanks for bringing this up!
